name: Java CI with Maven

on:
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: artifact
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Sample maven
        path: ${{GITHUB.WORKSPACE}}/Samplemaven/target/azure-functions/javafunctions
        
